packageExtensions:
  ts-jest@^25.2.0:
    dependencies:
      jest-config: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
