name: Node.js CI

on: [push]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Golang
        uses: actions/setup-go@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.1.0

      - name: Bootstrap repository
        run: npm run bootstrap

      - name: Build vendor libraries
        run: npm run build-vendor

      - name: Test project
        run: npm test -- --coverage

      - name: Build project
        run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
