name: Node.js CI

on: [push]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Golang
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build vendor libraries
        run: pnpm build-vendor

      - name: Test project
        run: pnpm test -- --coverage

      - name: Build project
        run: pnpm build

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Install Golang
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build vendor libraries
        run: pnpm build-vendor

      - name: Build project
        run: pnpm build

      - name: Publish to npm
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
