name: Node.js CI

on: [push]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Golang
        uses: actions/setup-go@v2

      - name: Install yarn
        run: npm i -g yarn

      - name: Link dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Build vendor libraries
        run: yarn build-vendor

      - name: Run tests
        run: yarn test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml
